### ISSUE TITLE
Include DataType HashMap in VAlgoLang

### ISSUE THREAD

**Issue by karthik-sivadas** [VAlgoLang/VAlgoLang#159]
It would be great if we can include HashMap datatype in Valgolang so that we can solve some of the problems faster and able to visualize them beautifully. Any ideas or plan to implement them?

I would love to help in any capacity possible.

**Comment by rbanerjee20** [comment]
Hello! That sounds like a great idea and thanks so much for bringing it up. We're actually a group of students and have got exams coming up this week, but perhaps we could start discussing how we would implement this after our exams are over?

And thanks very much for offering to help!

**Comment by karthik-sivadas** [comment]
> Hello! That sounds like a great idea and thanks so much for bringing it up. We're actually a group of students and have got exams coming up this week, but perhaps we could start discussing how we would implement this after our exams are over?
> 
> And thanks very much for offering to help!

That sounds great.

**Comment by rbanerjee20** [comment]
Hi @karthik-sivadas - we've finished our exams now and are more free to discuss adding HashMaps to VAlgoLang.

If you're interested in making a start, there's a page on the typical contributing workflow in our docs [here](https://valgolang.github.io/contributing.html). Essentially, what we did in the past when developing other datatypes was as follows:

* We first played around with the Manim code in the [Python library](https://valgolang.github.io/python_library.html) in order to work out how we would want that datatype animated. We did this by extending the `DataStructure` abstract base class in Python (available [here](https://github.com/VAlgoLang/VAlgoLang/blob/master/src/main/resources/python/data_structure.py))
* We then implemented this datatype in the compiler, as described step-by-step in the [contribution case study](https://valgolang.github.io/contributing.html#contribution-case-study-adding-lists)

Starting on the Manim side, it might be possible to implement HashMaps using some extension/variation on 2D arrays (since one way of visualising a HashMap with _n_ key-value pairs could be to use an 2 x _n_ array - although rehashing would have to be given more careful thought). Alternatively, we considered starting by creating a Set datatype (which would probably be visualised in a similar way to a resizable List) and then using that to build the HashMap.

There's probably a few different ways it could be done, and we're interested to see what you think!

**Comment by karthik-sivadas** [comment]
Sorry for the delay. Have been a little busy lately. I am also new to the whole concept of workings of data structure and basic algorithms we take for granted in the modern programming language. That was one of the reason why I was looking for visualization tools so I can create beautiful video, so that I can learn while teaching. VAlgoLang is a perfect tool for that as it doesn't require you to write extensive code as Manim. And coming to the point I think the second approach would be best as it would help to create another data structure while creating HashMap which is an added advantage. I will try to look into Manim more and any other possible solution during this weekend. And if you are going with the above approach can you please create issues as task if possible.

**Comment by rbanerjee20** [comment]
Hi - no problem at all.  

We've now created some Issues that we hope will clarify what needs to be done in order to implement HashMaps. If you'd like to help out, we suggest taking a look at #163 , which focuses on the Manim implementation of a linked list (which will be used to build up each bin in the HashMap). We'll be adding more links and info to that issue soon.

In the meantime, feel free to join our [Slack](https://join.slack.com/t/valgolang/shared_invite/zt-pbzwpgkk-RLs3kWM2~hr0P0boOwgCQQ), where we can discuss this in more depth and you can ask us any questions you may have.

Closing this issue so we can discuss this further on Slack.
